security:
    password_hashers:
        App\Entity\User:
            algorithm: auto
    enable_authenticator_manager: true

    # Gestion des utilisateurs
    providers:
        users:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls
    firewalls:
      dev:
        pattern: ^/_(profiler|wdt)
        security: false
      login:
        pattern: ^/api/login
        stateless: true
        json_login:
          check_path: api_login
          username_path: email
          password_path: password
          success_handler: App\Security\AuthenticationSuccessHandler
          #success_handler: lexik_jwt_authentication.handler.authentication_success
          failure_handler: lexik_jwt_authentication.handler.authentication_failure
      api:
        pattern: ^/api/
        stateless: true
        provider: users
        jwt: ~
        #main:
        #  stateless: true
        #  provider: users
        #  json_login:
        #    check_path: auth # The name in routes.yaml is enough for mapping
        #    username_path: email
        #    password_path: password
        #    success_handler: lexik_jwt_authentication.handler.authentication_success
        #    failure_handler: lexik_jwt_authentication.handler.authentication_failure
        #  jwt: ~

    access_control:
      - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }